# Copyright (c) 2023 Koji Hasegawa.
# This software is released under the MIT License.

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/deploy.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      unityVersion: 2022.3.13f1

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          lfs: false

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ env.unityVersion }}
          restore-keys: |
            Library-

      - name: Set CompressionFormat to Disabled
        run: |
          sed -i -e 's/webGLCompressionFormat: ./webGLCompressionFormat: 2/' ProjectSettings/ProjectSettings.asset
        # Note: Compression Format must be Disabled when deploy to GitHub Pages.

      - name: Set license secret key
        run: echo "secret_key=UNITY_LICENSE_$(echo ${{ env.unityVersion }} | cut -c 1-4)" >> "$GITHUB_ENV"

      - uses: game-ci/unity-builder@v4
        with:
          targetPlatform: WebGL
          unityVersion: ${{ env.unityVersion }} # Default is `auto`
          allowDirtyBuild: true # Modified ProjectSettings.asset
          versioning: Custom
          version: ${{ github.sha }}
        env:
          UNITY_LICENSE: ${{ secrets[env.secret_key] }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - uses: actions/upload-pages-artifact@v2
        with:
          path: build/WebGL/WebGL

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
