# Copyright (c) 2023 Koji Hasegawa.
# This software is released under the MIT License.

name: Meta file check

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]  # Same as default

jobs:
  meta-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          lfs: false

      - uses: DeNA/unity-meta-check@v3
